Formalize pipeline.yml

diff --git a/ci/repipe b/ci/repipe
--- a/ci/repipe
+++ b/ci/repipe
@@ -1,8 +1,5 @@
 #!/bin/bash
 
-CONCOURSE_TARGET=${CONCOURSE_TARGET:-sw-vsphere}
-PIPELINE=${PIPELINE:-slack-notification}
-
 cd $(dirname $BASH_SOURCE[0])
 echo "Working in $(pwd)"
 
@@ -11,10 +8,28 @@ if [[ -z "$VAULT_ADDR" ]] ; then
 	exit 1
 fi
 
+if [[ ! -f settings.yml ]]; then
+	echo >&2 "Missing local settings in ci/settings.yml!"
+	exit 1
+fi
+
 set -e
+trap "rm -f .deploy.yml" QUIT TERM EXIT INT
+spruce merge pipeline.yml settings.yml > .deploy.yml
+PIPELINE=$(spruce json .deploy.yml | jq -r '.meta.pipeline // ""')
+if [[ -z ${PIPELINE} ]]; then
+	echo >&2 "Missing pipeline name in ci/settings.yml!"
+	exit 1
+fi
+[ -n ${CONCOURSE_TARGET} ] && TARGET=${CONCOURSE_TARGET}
+if [[ -z ${TARGET} ]]; then
+	TARGET=$(spruce json .deploy.yml | jq -r '.meta.target // ""')
+fi
+if [[ -z ${TARGET} ]]; then
+	echo >&2 "Missing Concourse Target in ci/settings.yml!"
+	exit 1
+fi
 
-spruce merge pipeline.yml > live.yml
-
-fly --target ${CONCOURSE_TARGET} set-pipeline     --pipeline ${PIPELINE} --config live.yml
-fly --target ${CONCOURSE_TARGET} unpause-pipeline --pipeline ${PIPELINE}
-rm -f live.yml
+set +x
+fly --target ${TARGET} set-pipeline     --pipeline ${PIPELINE} --config .deploy.yml
+fly --target ${TARGET} unpause-pipeline --pipeline ${PIPELINE}
